Sylius/Stack

src/BootstrapAdminUi/templates/shared/crud/common/content/form.html.twig

Based on https://github.com/Sylius/Sylius/pull/17415

Fix form without data id

---

src/BootstrapAdminUi/templates/shared/crud/common/content/header/title_block.html.twig
src/BootstrapAdminUi/templates/shared/crud/common/navbar.html.twig
src/BootstrapAdminUi/templates/shared/crud/common/navbar/items.html.twig
src/BootstrapAdminUi/templates/shared/crud/common/navbar/menu.html.twig

[BootstrapAdminUi] Adjustments for mobile

---

docs/cookbook/admin_panel/index.md

Based on suggestions from #139

[Docs] Improve comments on how to add a new list of resources

---

src/BootstrapAdminUi/templates/shared/crud/index/content/grid/data_table.html.twig

[BootstrapAdminUi] Remove text-nowrap class

---

src/BootstrapAdminUi/assets/styles/_flashes.scss
src/BootstrapAdminUi/assets/styles/main.scss
src/BootstrapAdminUi/public/app.css
src/BootstrapAdminUi/public/app.rtl.css
src/BootstrapAdminUi/templates/shared/crud/common/content/flashes.html.twig

[BootstrapAdminUi] Close button to flash messages

---

compose.override.yaml
src/BootstrapAdminUi/templates/shared/grid/action/create.html.twig

Based on #https://github.com/Sylius/Sylius/pull/17564

[BootstrapAdminUi] Fix defining default value in twig templates

---

docs/SUMMARY.md
docs/grid/custom_action.md
docs/grid/custom_bulk_action.md
docs/grid/custom_field_type.md
docs/grid/custom_filter.md
docs/grid/field_configuration.md
docs/grid/index.md
docs/grid/your_first_grid.md

The sidebar menu was not synchronized with the grid index page.

[Docs] Fix Grid menu

---

docs/resource/configure_your_operations.md

https://stack.sylius.com/~/revisions/IhzXMXFotGeOvLDIL6nI/resource/index/configure_your_operations#configure-the-path

[Docs] Fix configuring path and short name

---

docs/README.md
docs/SUMMARY.md
docs/cookbook/admin_panel.md
docs/cookbook/admin_panel/index.md

Before
After
(of course, here we have the revision)

[Docs] Fix admin panel index page

---

src/BootstrapAdminUi/config/app/twig_hooks/layout/sidebar.php
src/BootstrapAdminUi/templates/shared/crud/common/sidebar/toggle_button.html.twig

Add toggle button

---

docs/cookbook/admin_panel/basic_operations.md
docs/cookbook/admin_panel/logo.md
docs/cookbook/admin_panel/page_titles.md

[Docs] Add tabs for Twig hooks

---

.editorconfig

Init editor config

---

app/Form/SpeakerAutocompleteType.php
app/Grid/Filter/SpeakerFilter.php
app/Grid/TalkGrid.php
config/packages/sylius_grid.yaml
config/routes/ux_autocomplete.yaml

[speaker-autocomplete.webm](https://github.com/user-attachments/assets/432c2816-952b-4845-ab3d-e8a40ba61242)

[TestApp] Use Autocomplete for the Speaker grid filter

---

.github/workflows/ci.yaml
.gitignore
app/Doctrine/Day.php
app/Doctrine/Month.php
app/Doctrine/Query/AST/Function/Day.php
app/Doctrine/Query/AST/Function/Month.php
app/Doctrine/Query/AST/Function/Year.php
app/Doctrine/Year.php
app/Repository/TalkRepository.php
app/Statistics/Provider/DayTalksProvider.php
app/Statistics/Provider/MonthTalksProvider.php
app/Statistics/Provider/StatisticsProvider.php
app/Statistics/ValueObject/Statistics.php
app/Twig/Component/StatisticsComponent.php
assets/app.js
assets/controllers.json
assets/scripts/statistics_chart.js
assets/styles/app.css
composer.json
config/packages/asset_mapper.yaml
config/packages/doctrine.yaml
config/sylius/twig_hooks/common/base.php
importmap.php
symfony.lock
templates/base.html.twig
templates/base/javascripts/app.html.twig
templates/dashboard/index/content/statistics_chart.html.twig

[statistics_chart.webm](https://github.com/user-attachments/assets/5f92328b-d6f5-40a5-92f8-3aa6b18236db)

[Demo] Statistics chart

---

app/Entity/Talk.php
app/Factory/TalkFactory.php
app/Grid/TalkGrid.php
app/Story/DefaultSyliusCon2024TalksStory.php
src/BootstrapAdminUi/templates/shared/grid/action/delete.html.twig
src/BootstrapAdminUi/templates/shared/grid/action/show.html.twig
src/BootstrapAdminUi/templates/shared/grid/action/update.html.twig

Fix action templates with url option

---

docs/SUMMARY.md
docs/cookbook/admin_panel.md
docs/cookbook/admin_panel/metatags.md
src/AdminUi/templates/base.html.twig

This pull request adds:
* a hook for adding metatags
* documentation for the hook
Solves https://github.com/Sylius/Stack/issues/274

Add metatags hook (favicon, seo, etc.)

---

src/BootstrapAdminUi/templates/shared/crud/common/content/header/title_block/actions.html.twig
src/BootstrapAdminUi/templates/shared/crud/index/content/grid/data_table.html.twig

Solves https://github.com/Sylius/Stack/issues/270
This issue only mentioned the main action group, but bulk actions were not sorted either

Sort main and bulk actions by position

---

src/BootstrapAdminUi/assets/styles/_body.scss
src/BootstrapAdminUi/assets/styles/_buttons.scss
src/BootstrapAdminUi/assets/styles/_form.scss
src/BootstrapAdminUi/assets/styles/_navbar.scss
src/BootstrapAdminUi/assets/styles/main.scss
src/BootstrapAdminUi/public/app.css
src/BootstrapAdminUi/public/app.rtl.css
src/BootstrapAdminUi/templates/shared/crud/common/content/header/title_block/actions.html.twig
templates/component/new_talks.html.twig

Related to https://github.com/Sylius/Sylius/pull/18026

WCAG improvements

---

src/AdminUi/templates/crud/create.html.twig
src/AdminUi/templates/crud/index.html.twig
src/AdminUi/templates/crud/show.html.twig
src/AdminUi/templates/crud/update.html.twig

Fixes #242
related to https://github.com/Sylius/Sylius/pull/17645

[BootstrapAdminUi] Allow configuring primary Twig hook for CRUD templates

---

src/BootstrapAdminUi/templates/shared/crud/index/content/header/breadcrumbs.html.twig

Fix missing dashboard path replacement
